package com.springbootproject.SpringBootRestService.entity;

import org.springframework.stereotype.Component;

// This is a simple JavaBean class that represents a Greeting object.
// In Spring Boot, this type of class is often used to transfer data between the controller and the view layer (or API).
// @Component marks this class as a Spring-managed component, meaning it will be automatically detected and registered as a bean in the Spring application context.
@Component
public class Greeting {

    // 'id' is a unique identifier for each Greeting object.
    // In a real-world application, this might be auto-generated by the database.
    private long id;

    // 'content' holds the message or text of the greeting.
    private String content;

    // Getter method for 'id'. This allows other classes to retrieve the value of 'id'.
    public long getId() {
        return id;
    }

    // Setter method for 'id'. This allows other classes to set or update the value of 'id'.
    public void setId(long id) {
        this.id = id;
    }

    // Getter method for 'content'. This allows other classes to retrieve the greeting message.
    public String getContent() {
        return content;
    }

    // Setter method for 'content'. This allows other classes to set or update the greeting message.
    public void setContent(String content) {
        this.content = content;
    }

}
